Http:
  Port: '8080'

Postgres:
  Url: 'postgres://postgres:password@0.0.0.0:5433/postgres?sslmode=disable&pool_max_conns=10'
  PoolMax: 2

Logger:
  Level: 'debug'

Telegram:
  Token: '5960953433:AAGl0Yul0tjBg8cZ4cgdQrcWXbqsTWtlEtw'
  Debug: false