Http:
  Port: '8080'

#     Example URL
#     postgres://jack:secret@pg.example.com:5432/mydb?sslmode=verify-ca&pool_max_conns=10
Postgres:
  PostgresUrl: 'postgres://jack:secret@pg.example.com:5432/mydb?sslmode=verify-ca&pool_max_conns=10'

Logger:
  Level: 'debug'

Telegram:
  Token: 'default-token'