name: CI
on: pull_request

jobs:
  codecov:
    name: runner / codecov
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  golangci-lint:
    name: runner / golang-ci-lint
    runs-on: self-hosted
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golang-ci-lint
        uses: reviewdog/action-golangci-lint@v2

  yamllint:
    name: runner / yaml-lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-yamllint@v1
        with:
          fail_on_error: true
          reporter: github-pr-review
          yamllint_flags: '-d "{extends: default, rules: {truthy: disable}}" .'

  dotenv-linter:
    name: runner / dotenv-linter
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: dotenv-linter/action-dotenv-linter@v2
        with:
          reporter: github-pr-review

  check-dependencies:
    name: runner / check-dependencies
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: WriteGoList
        run: go list -json -m all > go.list
      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
        continue-on-error: true

#  tests:
#    name: runner / tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-go@v4
#        with:
#          go-version: 1.20
#
#      - name: Unit Tests
#        run: "go test \
#          -v \
#          -race \
#          -covermode atomic \
#          -coverprofile=coverage.txt \
#          ./internal/..."
#      - name: Upload coverage report
#        run: bash <(curl -s https://codecov.io/bash)

#      - name: Integration tests
#        run: "docker-compose up \
#          --build \
#          --abort-on-container-exit \
#          --exit-code-from integration"
