name: Go Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Build
        run: go build cmd/app/main.go

      - name: Deploy
        run: |
          go run cmd/app/main.go